hathitrust/hathitrust_catalog_indexer

- solr/catalog/conf/schema.xml
Adds an auto-filled timestamp of time of index. Solr config only, requires nothing on the indexing side of the code.
> DEV-260: Add auto-filled timestamp of index, for sorting OAI requests

- indexers/common.rb
- indexers/ht.rb
- lib/ht_traject/ht_item.rb
`HT_NO_EXTERNAL_DATA` is equivalent to setting
`NO_DB` and `NO_REDIRECTS` and can be used going forward
as a way to disallow any external data for testing
purposes.
> Add new ENV variable "HT_NO_EXTERNAL_DATA"

- .github/workflows/build-manual.yml
- LICENSE.txt
- README.md
- example-index/Dockerfile
The first two stages (traject and solr) run under the current build architecture, since the goal there is to produce a platform-independent solr index. The final stage creates an image based on the platform-specific solr image that includes the solr core generated in the previous stage.
> Multiplatform example catalog build

- lib/ht_db_config.rb
- lib/ht_traject/ht_dbh.rb
If ht_secure_data.rb is present, that will be used instead.
> DEV-24: Use env vars for db connection info

- solr/catalog/conf/schema.xml
- solr/catalog/conf/schema/exactish_char_substitution.txt
- solr/catalog/conf/schema/text_types.xml
Adds a new `fieldType` called `exactishSort`, modeled on the one used in the umich config, and applies it to the title/author fields.
> Add new exactishSort type and use it

- lib/cictl/base_command.rb
- lib/cictl/commands.rb
- Logger factory and logger setup moved from `CICTL::Commands` to `CICTL::BaseCommand` initializer to restore access to `options[:log]` and `options[:verbose]`.
> TTO-86 cictl ignores --log option

- Dockerfile
- Gemfile
- Gemfile.lock
- For now use GitHub for the gem since rubygems.org doesn't have the new version.
- This introduces a dependency on git in the main Dockerfile.
- Should go back to using rubygems at a later date.
> Use mlibrary/canister 0.9.2 to try and mitigate threading issues.

- lib/cictl/index_command.rb
- lib/ht_traject/mock_redirects.rb
- lib/ht_traject/redirects.rb
- lib/services.rb
- spec/cictl/deleted_records_spec.rb
- spec/cictl/index_command_spec.rb
- spec/cictl/solr_command_spec.rb
- spec/ht_traject/redirects_spec.rb
- spec/spec_helper.rb
- remove preflight check for redirects file
- add helper for overriding services in tests
Tests pass for me with no stack issues. I did occasionally see the stack issues in the process of cleaning this up, but not with respect to the redirects file not being found. I suspect it might have been happening when something in `Services` was overridden, but the test failed and the original value wasn't restored. Using the provided `override_service` test helper should avoid that (i.e. the original value will be restored even if the test raises an exception)
@moseshll Assuming you're good with this, I'm good with the other branch then being merged to main.
> DEV-940/DEV-955 - simplify canister usage

- README.md
- lib/cictl/common.rb
- lib/cictl/index_command.rb
Catalog file names are named using the day before they were produced, as is noted in the README.
When we did the "full" index, this calls the `since` command which was intended to process all incremental files starting with the one produced on the same date as the full file up to the one produced on the current date.
However, `since` was subtracting a day from the start date, since its argument reflected the day the file was produced rather than the date in its name.
This PR makes handling for all commands taking dates consistent and updates the documentation to reflect that.
> DEV-627: "since" uses filenames embedded in date

- Dockerfile
- README.md
- docker-compose.yml
- lib/translation_maps/ht/collection_code_to_original_from.yaml
Brings our dockerfile up to current standards & allows building an image we can use in kubernetes for catalog indexing
* remove wait-for & use health checks
* use production stage
> Dockerfile updates for traject

- lib/cictl/solr_client.rb
This copies the authentication headers from the existing RSolr setup. Without this, the `post` ends up failing even with credentials in the URL. Not sure why, or if there's a better way to fix it -- I didn't dig into Faraday enough to figure that out.
> Attempt to fix auth issue for batch client

- README.md
- indexers/common_ht.rb
- lib/cictl/collection_map.rb
- lib/cictl/indexer.rb
- lib/services.rb
- spec/cictl/collection_map_spec.rb
Addresses #51 
aka DEV-1424 catalog indexer error writing collection map YAML
- Indexer no longer writes `lib/translation_maps/ht/collection_code_to_original_from.yaml`
- `CollectionMap` is now responsible for returning `Traject::TranslationMap` based on DB or existing YAML
- Traject indexing innards calls on `Services` for the map instead of loading YAML
- Remove instructions for janky workaround since collection_code_to_original_from.yaml should no longer be in constant flux
> 51 collection map should use database

- lib/cictl/index_command.rb
- lib/services.rb
- spec/cictl/index_command_spec.rb
We were checking for a full journal file but not writing one when we did the full index, leading to a situation where regardless of journal file presence the "continue" command would do a full reindex every day.
This refactors the `all` command some, and tests that we are writing both the full and update journal files.
> DEV-1440 - write journal when indexing full file

- Dockerfile
- lib/cictl/index_command.rb
- spec/cictl/index_command_spec.rb
`cictl index continue` was checking only that the full journal existed (and checking that multiple times)... This should correct the observed behavior where it is not indexing additional daily files after doing the full run.
> DEV-973: check correct journal file for continue

- README.md
- lib/ht_traject/redirects.rb
- Replace hardcoded path with new ENV `REDIRECTS_DIR` also found in the `hathifiles` repo.
- I'm not particularly happy with the "current month falling back to last month" logic for finding default redirects file.
- Seems like an error if this month's redirect is not present.
- Addressing this should be an item for discussion and possible future work.
> DEV-1409 move redirects to /htapps/archive/redirects

- Gemfile.lock
- spec/cictl/index_command_spec.rb
- Modify Faraday delete call to remove the (blank) instance/JOB_NAMESPACE
- See https://github.com/prometheus/pushgateway/issues/225
> - Update to push_metrics 0.10.0

- docker-compose.yml
- lib/services.rb
- Change connection string to use new ENV names
- Add note about connection string being the anointed method for JDBC connections in Sequel (alas)
- Remove `NO_DB` env in docker compose so we exercise the DB connection a bit in our tests
> DEV-1475 catalog indexing: update what env vars it uses for the database

- solr/solrcloud/conf/solrconfig.xml
This is a tidy PR to set up Transaction logs to Catalog clusters in cloud mode
> Configuring Catalog transaction logs

- Gemfile.lock
- README.md
- lib/ht_traject/oclc_resolution.rb
- spec/ht_traject/oclc_resolution_spec.rb
DEV-1516 rename oclc concordance fields
- Rename fields in `lib/ht_traject/oclc_resolution.rb` Sequel query
- Add very basic `OCLCResolution` spec.
> Dev 1516 rename oclc concordance fields

- Gemfile.lock
- README.md
- lib/cictl/index_command.rb
- lib/cictl/stop_release.rb
- spec/cictl/index_command_spec.rb
- spec/cictl/stop_release_spec.rb
- spec/spec_helper.rb
- Add `StopRelease` class that handles writing and removing `STOPCATALOGRELEASE` file in `FLAGS_DIRECTORY`
- `cictl index` commands use `preflight` and `postflight` to read and remove these, respectively
- Changes to README and test helper to reflect addition of `FLAGS_DIRECTORY`
Note: `ht_tanka` changes made in parallel, q.v.
Further note: addressing CVE-2025-27221 here because Dependabot may have issues proposing fixes for JRuby. This is a minimalist `bundle update --conservative uri` version bump.
> DEV-1578 Only release catalog if indexing succeeds

- Gemfile.lock
- lib/cictl/solr_client.rb
To address `RSolr::Error::Timeout` after commit for metadata-processong workflow
> Up SolrClient default timeout from 15 to 120 seconds

- solr/solrcloud/Dockerfile
- solr/solrcloud/README.md
This PR (pull request) changes the Dockerfile, upgrading the Solr image from Solr 8.11.2 to Solr 8.11.4. It is related to another PR on [argocd-kubeadmin](https://github.com/hathitrust/argocd-kubeadmin) repository that updates the image used on the Solr operator. 
As part of this update, the process to create a Solr backup has been tested. The `solr/solrcloud/README.md` file has been updated with the command used to create backups of solr collections.
> Upgrade Solr version. From Solr 8.11.2 to Solr 8.11.4
